# Problem 1 

In [58]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
x = np.array([5,7,4,1,2])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
x.sort()
print(x)

[1 2 4 5 7]


# Problem 2

In [56]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a = np.array([10,15,30,45,60])
print(a)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
import random
b = np.random.randint(5,15,4)
print(b)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
x = np.arange(50,100,5)
print(x)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
np.zeros(10)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
np.ones(10)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
y = np.linspace(0,100,5)
print(y)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
z = np.random.randint(10,30,5)
print(z)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
k = np.random.uniform(-1,1,10)
print(k)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
m = np.random.randint(10,50, size = (3,5))
print(m)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(m.sum(axis=1))
print(m.sum(axis=0))
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(f"En büyük değer: {np.max(m)}")
print(f"En küçük değer: {np.min(m)}")
print(f"Ortalama: {np.mean(m)}")
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(np.argmax(m))

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
dizi = np.arange(10,20)
print(dizi[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(dizi[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(m[0,:])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(m[1,2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(m[0:3,0:1])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(np.power(m,2))

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
matris = np.random.randint(-50,50, size = (3,5))
print(matris)
print(matris[(matris > 0) & (matris % 2 == 0)])

[10 15 30 45 60]
[9 6 6 9]
[50 55 60 65 70 75 80 85 90 95]
[  0.  25.  50.  75. 100.]
[20 24 28 25 27]
[ 0.8559711   0.71881577  0.8595036   0.76434253 -0.77866159  0.1633792
 -0.67711205  0.08718478  0.21096707  0.00690732]
[[24 27 37 45 34]
 [49 17 23 18 20]
 [18 15 20 42 49]]
[167 127 144]
[ 91  59  80 105 103]
En büyük değer: 49
En küçük değer: 15
Ortalama: 29.2
5
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]
[24 27 37 45 34]
23
[[24]
 [49]
 [18]]
[[ 576  729 1369 2025 1156]
 [2401  289  529  324  400]
 [ 324  225  400 1764 2401]]
[[ 16 -18  32  16 -37]
 [-49  22  39  29  -1]
 [ -7 -27   3  -7 -44]]
[16 32 16 22]
